# Generated by Django 3.1.6 on 2021-02-09 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=110, unique=True, verbose_name='slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=110, unique=True, verbose_name='slug')),
                ('description', models.TextField(max_length=800, verbose_name='description')),
                ('release_date', models.DateField(verbose_name='release_date')),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='runtime')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('genres', models.ManyToManyField(related_name='videos', to='media_server.Genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
